services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file: ./server/.env
    ports:
      - "5000:5000"
  front:
    build: ./web
    container_name: front
    restart: always
    env_file:
      - ./web/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
